name: CI build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.71
    - name: build
      run: ./build.sh

  build-rel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.71
    - name: build-rel
      run: CMAKE_BUILD_TYPE=Release ./build.sh
    - name: Stage files for upload to GitHub Pages
      run: |
        mkdir deploy
        cp build_rel/client.* deploy/
        mv deploy/client.html deploy/index.html
    - name: Upload files to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build-rel
    permissions:
      pages: write  # Permissions needed to deploy to GitHub Pages
      id-token: write  # Permissions needed for OIDC authentication
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
